import './globals.css';

import type {
  Metadata,
} from 'next';
import type { PropsWithChildren } from 'react';

import { goormSansFont } from '@/assets/fonts';
import Footer from '@/components/service/Footer';
import Header from '@/components/service/Header';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={goormSansFont.className}
        style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange enableSystem>
          <Header
            menuItems={[
              {
                label: 'About',
                href: '#about',
              },
              {
                label: 'Skills',
                href: '#skills',
              },
              {
                label: 'Careers',
                href: '#careers',
              },
            ]}
            title=""
          />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
