import './globals.css';

import type {
  Metadata,
} from 'next';
import {
  Geist, Geist_Mono,
} from 'next/font/google';
import type { PropsWithChildren } from 'react';

import Footer from '@/components/service/Footer';
import Header from '@/components/service/Header';
import { ThemeProvider } from '@/components/theme-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange enableSystem>
          <Header
            menuItems={[
              {
                label: 'About',
                href: '#about',
              },
              {
                label: 'Skills',
                href: '#skills',
              },
              {
                label: 'Projects',
                href: '#projects',
              },
            ]}
            title=""
          />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
