import { registerEnumType } from '@nestjs/graphql';

export enum TechLogo {
  React = 'React',
  ReactNative = 'ReactNative',
  Sass = 'Sass',
  Vue = 'Vue',
  Java = 'Java',
  Python = 'Python',
  Docker = 'Docker',
  MySQL = 'MySQL',
  Spring = 'Spring',
  SpringBoot = 'SpringBoot',
  Grails = 'Grails',
  Hibernate = 'Hibernate',
  NextJS = 'NextJS',
  ApolloClient = 'ApolloClient',
  PostgreSQL = 'PostgreSQL',
  Oracle = 'Oracle',
  MongoDB = 'MongoDB',
  Yarn = 'Yarn',
  Vite = 'Vite',
  AntDesign = 'AntDesign',
  Storybook = 'Storybook',
  ECharts = 'ECharts',
  MaterialUI = 'MaterialUI',
  Redux = 'Redux',
  Recoil = 'Recoil',
  TypeScript = 'TypeScript',
  Nginx = 'Nginx',
  ApacheTomcat = 'ApacheTomcat',
  GithubActions = 'GithubActions',
}

registerEnumType(TechLogo, {
  name: 'TechLogo',
  description: '프레임워크, 라이브러리 로고',
  valuesMap: {
    React: { description: 'React' },
    ReactNative: { description: 'React Native' },
    Sass: { description: 'Sass (SCSS)' },
    Vue: { description: 'Vue.js' },
    Java: { description: 'Java' },
    Python: { description: 'Python' },
    Docker: { description: 'Docker' },
    MySQL: { description: 'MySQL Database' },
    Spring: { description: 'Spring MVC' },
    SpringBoot: { description: 'Spring Boot' },
    Grails: { description: 'Grails' },
    Hibernate: { description: 'Hibernate' },
    NextJS: { description: 'Next.js' },
    ApolloClient: { description: 'Apollo Client' },
    PostgreSQL: { description: 'PostgreSQL Database' },
    Oracle: { description: 'Oracle Database' },
    MongoDB: { description: 'MongoDB' },
    Yarn: { description: 'Yarn' },
    Vite: { description: 'Vite' },
    AntDesign: { description: 'Ant Design' },
    Storybook: { description: 'Storybook' },
    ECharts: { description: 'ECharts.js' },
    MaterialUI: { description: 'Material UI' },
    Redux: { description: 'Redux' },
    Recoil: { description: 'Recoil' },
    TypeScript: { description: 'TypeScript' },
    Nginx: { description: 'Nginx' },
    ApacheTomcat: { description: 'Apache Tomcat' },
    GithubActions: { description: 'Github Actions' },
  },
});
