query Resume {
  resume: Resume_get {
    title
    github
    history {
      companyName
      logo {
        src
        alt
        width
        height
      }
      startDate
      endDate
      website
      description
      carriers {
        groupName
        list {
          name
          completed
          startDate
          endDate
          techList
          description
        }
      }
    }
  }
}
