query Resume($userId: String!) {
  resume(userId: $userId) {
    title
    github
    companyList {
      companyId
      companyName
      logo {
        src
        alt
        width
        height
      }
      startDate
      endDate
      website
      description
      projectList {
        groupName
        list {
          projectId
          title
          startDate
          endDate
          techList
          description
        }
      }
    }
  }
}