type Query {
  getResume: Resume!
}

type Resume {
  title: String!
  github: String
  resumeList: [ResumeItem!]!
}

type ResumeItem {
  name: String!
  logo: StaticImageData
  startDate: String!
  endDate: String
  website: String
  description: String
  carrierList: [Carrier!]!
}

type StaticImageData {
  src: String!
  alt: String!
  width: Int!
  height: Int!
}

type Carrier {
  groupName: String
  list: [CarrierItem!]!
}

type CarrierItem {
  name: String!
  completed: Boolean!
  startDate: String!
  endDate: String!
  techList: [Logo!]!
  description: String!
}

enum Logo {
  React
  ReactNative
  Sass
  Vue
  Java
  Python
  Docker
  MySQL
  Spring
  SpringBoot
  NextJS
  ApolloClient
  PostgreSQL
  Oracle
  MongoDB
  Yarn
  Vite
  AntDesign
  Storybook
  MUi
  Redux
  TypeScript
  Nginx
  ApacheTomcat
}
