name: Github Pages

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-verseion: 16.x
      
      - name: Install
        run: yarn

      - name: Build
        run: yarn build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGE_TOKEN }}
          publish_dir: ./docs