name: jayur830.github.io-server-nestjs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3

      - name: fly deploy
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy